create extension if not exists pgcrypto;

create type household_role as enum ('owner', 'member');
create type task_status as enum ('Idee','Zu prüfen','Geplant','Einkauf notwendig','Zur Umsetzung bereit','In Arbeit','Wartet','Erledigt','Verworfen');
create type task_category as enum ('Reparatur','Renovierung','Einrichtung','Organisation','Reinigung','Beleuchtung','Elektrik','Sanitär','Möbel','Dekoration','Sicherheit','Energie','Sonstiges');
create type effort_class as enum ('unter 15 Minuten','15–30 Minuten','30–60 Minuten','1–2 Stunden','halber Tag','ganzer Tag','mehrere Tage','noch unbekannt');
create type difficulty_level as enum ('sehr einfach','einfach','mittel','anspruchsvoll','Fachbetrieb erforderlich');
create type shopping_status as enum ('benötigt','recherchieren','ausgewählt','bestellt','gekauft','nicht mehr benötigt');
create type attachment_type as enum ('Problemfoto','Vorher-Foto','Inspirationsfoto','Produktfoto','Nachher-Foto','sonstiger Anhang');
create type measurement_unit as enum ('mm','cm','m','m²','Stück');

create table households (id uuid primary key default gen_random_uuid(), name text not null, currency text not null default 'EUR', created_at timestamptz not null default now(), created_by uuid not null references auth.users(id), deleted_at timestamptz);
create table household_members (household_id uuid references households(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, role household_role not null default 'member', joined_at timestamptz not null default now(), primary key (household_id, user_id));
create table rooms (id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id) on delete cascade, name text not null, room_type text, description text, display_order int not null default 0, cover_image_path text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table tasks (id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id) on delete cascade, room_id uuid not null references rooms(id) on delete cascade, title text not null, description text, category task_category not null default 'Sonstiges', status task_status not null default 'Idee', owner_user_id uuid references auth.users(id), manual_importance int check (manual_importance between 1 and 5), urgency int not null default 3 check (urgency between 1 and 5), benefit int not null default 3 check (benefit between 1 and 5), delay_risk int not null default 3 check (delay_risk between 1 and 5), disturbance_frequency int not null default 3 check (disturbance_frequency between 1 and 5), dependency_impact int not null default 1 check (dependency_impact between 1 and 5), calculated_priority int generated always as (round((((urgency - 1) * 25) * 0.30) + (((benefit - 1) * 25) * 0.20) + (((delay_risk - 1) * 25) * 0.25) + (((disturbance_frequency - 1) * 25) * 0.15) + (((dependency_impact - 1) * 25) * 0.10))) stored, effort_class effort_class default 'noch unbekannt', difficulty difficulty_level default 'mittel', estimated_hours_min numeric, estimated_hours_likely numeric, estimated_hours_max numeric, estimated_cost_min numeric, estimated_cost_likely numeric, estimated_cost_max numeric, actual_cost numeric, due_date date, target_period text, completed_at timestamptz, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check ((status = 'Erledigt' and completed_at is not null) or status <> 'Erledigt'));
create table task_dependencies (task_id uuid references tasks(id) on delete cascade, depends_on_task_id uuid references tasks(id) on delete cascade, primary key (task_id, depends_on_task_id), check (task_id <> depends_on_task_id));
create table shopping_items (id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id) on delete cascade, task_id uuid references tasks(id) on delete set null, name text not null, quantity numeric default 1, unit text, estimated_unit_price numeric, actual_unit_price numeric, vendor text, product_url text, status shopping_status not null default 'benötigt', material_type text not null default 'Verbrauchsmaterial' check (material_type in ('Werkzeug','Verbrauchsmaterial')), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table task_notes (id uuid primary key default gen_random_uuid(), task_id uuid not null references tasks(id) on delete cascade, author_user_id uuid not null references auth.users(id), content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table attachments (id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id) on delete cascade, task_id uuid references tasks(id) on delete cascade, room_id uuid references rooms(id) on delete cascade, attachment_type attachment_type not null, storage_path text not null, original_filename text, mime_type text not null, size_bytes bigint not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), check (task_id is not null or room_id is not null));
create table measurements (id uuid primary key default gen_random_uuid(), task_id uuid not null references tasks(id) on delete cascade, label text not null, value numeric not null, unit measurement_unit not null, notes text, created_at timestamptz not null default now());
create table activity_log (id uuid primary key default gen_random_uuid(), household_id uuid not null references households(id) on delete cascade, user_id uuid references auth.users(id), entity_type text not null, entity_id uuid not null, action text not null, change_summary jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create function is_household_member(target_household uuid) returns boolean language sql security definer stable set search_path = public as $$ select exists (select 1 from household_members where household_id = target_household and user_id = auth.uid()) $$;
create function add_household_creator_as_owner() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into household_members (household_id, user_id, role) values (new.id, new.created_by, 'owner') on conflict do nothing; return new; end; $$;
create trigger households_add_owner after insert on households for each row execute function add_household_creator_as_owner();
create function is_household_owner(target_household uuid) returns boolean language sql security definer stable set search_path = public as $$ select exists (select 1 from household_members where household_id = target_household and user_id = auth.uid() and role = 'owner') $$;
create function prevent_cyclic_task_dependencies() returns trigger language plpgsql as $$ begin if exists (with recursive chain(task_id, depends_on_task_id) as (select new.task_id, new.depends_on_task_id union select td.task_id, td.depends_on_task_id from task_dependencies td join chain c on td.task_id = c.depends_on_task_id) select 1 from chain where depends_on_task_id = new.task_id) then raise exception 'cyclic task dependency'; end if; return new; end; $$;
create trigger task_dependencies_no_cycle before insert or update on task_dependencies for each row execute function prevent_cyclic_task_dependencies();

alter table households enable row level security; alter table household_members enable row level security; alter table rooms enable row level security; alter table tasks enable row level security; alter table task_dependencies enable row level security; alter table shopping_items enable row level security; alter table task_notes enable row level security; alter table attachments enable row level security; alter table measurements enable row level security; alter table activity_log enable row level security;
create policy households_select on households for select using (is_household_member(id)); create policy households_insert on households for insert with check (created_by = auth.uid()); create policy households_update_owner on households for update using (is_household_owner(id));
create policy members_select on household_members for select using (is_household_member(household_id)); create policy members_owner_insert on household_members for insert with check (is_household_owner(household_id)); create policy members_owner_update on household_members for update using (is_household_owner(household_id)) with check (is_household_owner(household_id)); create policy members_owner_delete on household_members for delete using (is_household_owner(household_id));
create policy rooms_member_all on rooms for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy tasks_member_all on tasks for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy task_dependencies_member_all on task_dependencies for all using (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id))) with check (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id)));
create policy shopping_member_all on shopping_items for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy notes_member_all on task_notes for all using (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id))) with check (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id)));
create policy attachments_member_all on attachments for all using (is_household_member(household_id)) with check (is_household_member(household_id));
create policy measurements_member_all on measurements for all using (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id))) with check (exists (select 1 from tasks t where t.id = task_id and is_household_member(t.household_id)));
create policy activity_member_select on activity_log for select using (is_household_member(household_id)); create policy activity_member_insert on activity_log for insert with check (is_household_member(household_id));
